services:
  api:
    image: asia-northeast3-docker.pkg.dev/pico-503205/pico-be/api:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  redis-data:
